import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/authContex";
import BannerModal from "./components/modals/banner/BannerModal";
import VoucherModal from "./components/modals/voucher/VoucherModal";
import AdminModal from "./components/modals/admin/AdminModal";
import MerchantModal from "./components/modals/merchant/MerchantModal";
import MenuModal from "./components/modals/menu/MenuModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mopesan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <MenuModal />
          {/* <BannerModal /> */}
          <VoucherModal />
          <AdminModal />
          <MerchantModal />
          {children}</body>
      </AuthProvider>
    </html>
  );
}
