import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/authContex";
import Modal from "./components/modals/Modal";
import MenuModal from "./components/modals/MenuModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mopesan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <MenuModal />
          {children}</body>
      </AuthProvider>
    </html>
  );
}
